language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t knoxnoe/webnoe:latest .
  - docker push knoxnoe/webnoe:latest
